version: '3.5'

services:
  traefik:
    image:  traefik:alpine
    networks:
      - traefik-network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./traefik.toml:/traefik.toml
      - ./certs:/etc/traefik/certs
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      traefik.enable: "true"
      traefik.port: "8080"
      traefik.backend: "traefik"
      traefik.frontend.rule: "Host:traefik.local"
    restart: always
networks:
  traefik-network:
    name: traefik-network
