# debug = true
# logLevel = "VERBOSE"

InsecureSkipVerify = true
exposedbydefault = true
swarmmode = false

defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      certFile = "/etc/traefik/certs/localhost.crt"
      keyFile = "/etc/traefik/certs/localhost.key"

[web]
address = ":8080"
defaultEntryPoints = ["http"]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "traefik.local"
watch = true

