version: '3'

networks:
  traefik-network:
    external: true
  internal:
    external: false

services:
  mysql:
    image: mysql:latest
    volumes:
      - "./data/db:/var/lib/mysql"
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    networks:
      - internal
    labels:
      - traefik.enable=false

  mailcatcher:
    image: schickling/mailcatcher
    restart: always
    environment:
      MAILCATCHER_PORT: 1025
    labels:
      - 'traefik.backend=mailcatcher_site2'
      - 'traefik.port=1080'
      - 'traefik.frontend.rule=Host:mailcatcher.site2.local'
      - 'traefik.docker.network=traefik-network'
    networks:
      - internal
      - traefik-network

  memcached:
    image: memcached:latest
    restart: always
    networks:
      - internal
    labels:
      - traefik.enable=false

  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:5.6.5
  #   restart: always
  #   environment:
  #     ES_JAVA_OPTS: "-Xms750m -Xmx750m"
  #   ports:
  #     - "9200:9200"
  #   volumes:
  #     - "./config/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
  #     - "./config/elasticsearch/plugins:/usr/share/elasticsearch/plugins"
  phpfpm:
    image: 10up/phpfpm
    depends_on:
      - mysql
      - memcached
      # - elasticsearch
    volumes:
      - "./wordpress:/var/www/html"
      - "./config/php-fpm/php.ini:/usr/local/etc/php/php.ini"
      - "./config/php-fpm/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini"
      - ~/.ssh:/root/.ssh
    restart: always
    networks:
      - internal
    labels:
      - traefik.enable=false
  nginx:
    depends_on:
      - phpfpm
    labels:
      - traefik.backend=site2
      - traefik.frontend.rule=Host:site2.local
      - traefik.docker.network=traefik-network
      - traefik.port=80
    networks:
      - internal
      - traefik-network
    image: nginx:latest
    volumes:
      - "./wordpress:/var/www/html"
      - "./config/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./config/certs:/etc/nginx/certs"
      - "./logs/nginx:/var/log/nginx"
    restart: always

  # wpsnapshots:
  #   image: 10up/wpsnapshots
  #   depends_on:
  #     - mysql
  #     - phpfpm
  #   volumes:
  #     - "./config/wpsnapshots:/wpsnapshots"
  #     - "./wordpress:/var/www/html"
  #   labels:
  #     - traefik.enable=false
  #   networks:
  #     - internal

  # wordmove:
  #   image: mfuezesi/wordmove
  #   depends_on:
  #     - nginx
  #   tty: true
  #   restart: on-failure:5
  #   volumes:
  #     - "./wordmove:/home"
  #     - "./wordpress:/var/www/html"
  #     - "~/.ssh:/root/.ssh"
  #   labels:
  #     - traefik.enable=false
  #   networks:
  #     - internal

